### ISSUE TITLE
Setting the number of frets to a number higher than five crashes the webpage

### ISSUE THREAD

**Issue by fernandoGubiMarques** [EFHIII/midi-ch#1]
I figured setting the number of frets to 6 would be useful for charting to GH Live controllers, but it just freezes to note display, and you got to reload the page to get it working again.

**Comment by EFHIII** [comment]
Sorry I didn't see this sooner. Ignoring that 6 frets in line probably doesn't translate very well to GH Live, you could get effectively that kind of chart by enabling open-fret, although open-fret chords don't get charted (for obvious reasons). I put in a safe guard so that if you try setting frets to a number >5, it'll just set it back to 5, thereby fixing the problem of it freezing. I don't know how I didn't catch that before; I even wrote a modified version of the code that outputs 10-fret (5-fret x2) and didn't notice the bug then.
